### ISSUE TITLE
No se deben incluir estilos incrustados

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/proyecto2021-gomezpizarro#1]
El estilo de los elementos debe establecerse en un archivo CSS (prohibido emplear estilos incrustados).

https://github.com/UCC-LabCompu2/proyecto2021-gomezpizarro/blob/c2ac30f059c54a41472e2938e3069e164b62dce7/index.html#L10-L12

**Comment by GonzaGomezPizarro** [comment]
DONE
