### ISSUE TITLE
Mejora: Página de Loading

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/proyecto2021-gomezpizarro#13]
En lugar de que se carguen múltiples barras de loading, emplear una sola en el centro de la página.

**Comment by edme88** [comment]
La mejora sugerida por email con el cover debe estar implementada.

**Comment by GonzaGomezPizarro** [comment]
Pierde la calidad de la imagen y ademas queda mejor que sean muchas barras de carga

**Comment by GonzaGomezPizarro** [comment]
Queda mejor que sean muchas barras de carga , si pongo una sola pierde la calidad al agrandarse la imagen y pierde su estilo
