### ISSUE TITLE
En JUEGO.HTML el index permite ingresar más de 4 cifras

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/proyecto2021-gomezpizarro#14]
![imagen](https://user-images.githubusercontent.com/8345007/120939737-c8022800-c6ef-11eb-9f17-3830c9e19403.png)

**Comment by GonzaGomezPizarro** [comment]
done

**Comment by GonzaGomezPizarro** [comment]
Deja entrar pero te salta un aviso y vuelve a pedir la informacion
