### ISSUE TITLE
Error en la lógica/flujo del programa

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/proyecto2021-gomezpizarro#19]
En la siguiente pantalla:
![imagen](https://user-images.githubusercontent.com/8345007/122820221-c3be3900-d2b1-11eb-8797-f632aeec55c5.png)
Ingrese 2 veces los valores de manera incorrecta.

En la primera ocasión ingrese:
-1
5
Mostro el mensaje de error
![imagen](https://user-images.githubusercontent.com/8345007/122820358-e2243480-d2b1-11eb-8b62-1b8e28a5f86a.png)
Ingrese:
a
6
![imagen](https://user-images.githubusercontent.com/8345007/122820405-f1a37d80-d2b1-11eb-9b24-e8944d3f81a5.png)

y me dejo avanzar en la página
![imagen](https://user-images.githubusercontent.com/8345007/122820432-fb2ce580-d2b1-11eb-9d79-743367b77a3d.png)

**Comment by GonzaGomezPizarro** [comment]
correjido
