### ISSUE TITLE
Los intentos de la máquina y lo que responde el usuario no quedan almacenados en ningun sitio

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/proyecto2021-gomezpizarro#20]
Habría que considerar la posibilidad de que los valores ingresados por el usuario aparezcan también en el canvas (o en un canvas aparte) para que quede registro.
![imagen](https://user-images.githubusercontent.com/8345007/122820723-4e069d00-d2b2-11eb-84ee-dcc4bfbed796.png)

**Comment by GonzaGomezPizarro** [comment]
error solucionado, ahora se puede ver el intento que hace la maquina, junto con sus bien y regular
